### ISSUE TITLE
2005 build of HL2

### ISSUE THREAD

**Issue by ghost** [x8BitRain/hl-archive#4]

**Comment by x8BitRain** [comment]
Hi, this repo isn't for distributing the builds but just for documenting known to exist build numbers of games, I can suggest you ask in either the SourceRuns discord or the Valve Archive discord channels for the actual builds, you can find the invites through google search.

**Comment by tjd2** [comment]
> Hi, this repo isn't for distributing the builds but just for documenting known to exist build numbers of games, I can suggest you ask in either the SourceRuns discord or the Valve Archive discord channels for the actual builds, you can find the invites through google search.

I have asked there, but nobody had it

**Comment by x8BitRain** [comment]
> I have asked there, but nobody had it

Ask in SourceRuns discord then.
